server:
  port: 8082
myspcloud:
  item:
    url: http://127.0.0.1:8081/item/
spring:
  application:
    name: app-order
eureka:
  client:
    service-url:
      defaultZone: http://fhf:123456@127.0.0.1:8100/eureka,http://fhf:123456@127.0.0.1:9100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true